export const constants = {
  BASE_URL: '/api/v1',
  ENDPOINTS: {
    COMPANY: 'company',
    SHARED: 'shared',
    AUTH: 'auth',
    PROFESSIONAL: 'professional',
    PROFESSIONAL_COMPANY: 'professional-company',
    CUSTOMER: 'customer',
    USER: 'user',
    COLLABORATOR: 'collaborator',
    EVENTS: 'events',
    INVENTORY: 'inventory',
    ADMIN: 'admin',
    SERVICE: 'service',
    APPOINTMENTS: 'appointments',
    APPOINTMENT_REVIEWS: 'appointment-reviews',
    PROFESSIONAL_SHOWCASES: 'professional-showcases',
    SUSCRIPTIONS: 'suscriptions',
  },
};
